## Version 2024/07/16
# Upstream container name must match the app service in docker-compose.yml.

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name kofc.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
    large_client_header_buffers 4 16k;

    location /api/image {
        proxy_cache next_image;
        proxy_cache_key "$scheme$host$request_uri";
        proxy_cache_valid 200 365d;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        add_header X-Image-Cache $upstream_cache_status always;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app app;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location /_next/image {
        proxy_cache next_image;
        proxy_cache_key "$scheme$host$request_uri";
        proxy_cache_valid 200 365d;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        add_header X-Image-Cache $upstream_cache_status always;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app app;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app app;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
